import { Fortune } from "@/lib/types";

export const FORTUNES: Fortune[] = [
  {
    id: "tarot",
    name: "タロット占い",
    nameEn: "Tarot",
    description: "22枚の大アルカナカードであなたの運命を読み解きます",
    origin: "ヨーロッパ",
    icon: "🃏",
    category: "cards",
    inputType: "question",
  },
  {
    id: "astrology",
    name: "西洋占星術",
    nameEn: "Western Astrology",
    description: "生まれた日の星の配置があなたの性格と運命を示します",
    origin: "バビロニア・ギリシャ",
    icon: "♈",
    category: "astrology",
    inputType: "birthday_time",
  },
  {
    id: "numerology",
    name: "数秘術",
    nameEn: "Numerology",
    description: "名前と生年月日から導き出す数字があなたの本質を示します",
    origin: "ピタゴラス・古代ギリシャ",
    icon: "🔢",
    category: "numbers",
    inputType: "birthday_name",
  },
  {
    id: "shichu-suimei",
    name: "四柱推命",
    nameEn: "Bazi (Four Pillars)",
    description: "生年月日時から四本の柱を立て、運命の流れを読みます",
    origin: "中国",
    icon: "🀄",
    category: "eastern",
    inputType: "birthday_time",
  },
  {
    id: "iching",
    name: "易経",
    nameEn: "I Ching",
    description: "3000年以上の歴史を持つ中国の易で今の状況を占います",
    origin: "中国",
    icon: "☯️",
    category: "eastern",
    inputType: "question",
  },
  {
    id: "rune",
    name: "ルーン占い",
    nameEn: "Rune Divination",
    description: "古代北欧の文字ルーンがあなたへのメッセージを伝えます",
    origin: "北欧",
    icon: "ᚠ",
    category: "cards",
    inputType: "question",
  },
  {
    id: "kyusei-kigaku",
    name: "九星気学",
    nameEn: "Nine Star Ki",
    description: "生まれた年の星が示す今年の運気と方位を読みます",
    origin: "中国・日本",
    icon: "⭐",
    category: "eastern",
    inputType: "birthday",
  },
  {
    id: "blood-type",
    name: "血液型占い",
    nameEn: "Blood Type",
    description: "血液型から性格・相性・今日の運勢を読み解きます",
    origin: "日本",
    icon: "🩸",
    category: "nature",
    inputType: "blood_type",
  },
  {
    id: "omikuji",
    name: "おみくじ",
    nameEn: "Omikuji",
    description: "神様からの一言。今日の運勢を神籤で引きます",
    origin: "日本",
    icon: "🎋",
    category: "nature",
    inputType: "draw",
  },
  {
    id: "oracle",
    name: "オラクルカード",
    nameEn: "Oracle Cards",
    description: "天使や精霊からのメッセージをカードで受け取ります",
    origin: "西洋",
    icon: "✨",
    category: "cards",
    inputType: "question",
  },
  {
    id: "dream",
    name: "夢占い",
    nameEn: "Dream Interpretation",
    description: "夢に現れたシンボルからあなたの深層心理を探ります",
    origin: "世界共通",
    icon: "💭",
    category: "nature",
    inputType: "keyword",
  },
  {
    id: "angel-number",
    name: "エンジェルナンバー",
    nameEn: "Angel Number",
    description: "繰り返し見る数字に込められた天使のメッセージを読みます",
    origin: "新時代思想",
    icon: "👼",
    category: "numbers",
    inputType: "keyword",
  },
  {
    id: "feng-shui",
    name: "風水",
    nameEn: "Feng Shui",
    description: "生まれた年の属性から今年の吉方位と開運法を伝えます",
    origin: "中国",
    icon: "🧭",
    category: "eastern",
    inputType: "birthday",
  },
  {
    id: "birthstone",
    name: "誕生石占い",
    nameEn: "Birthstone",
    description: "誕生月の石が持つ力があなたへのメッセージを示します",
    origin: "世界共通",
    icon: "💎",
    category: "nature",
    inputType: "birthday",
  },
  {
    id: "hand-reading",
    name: "手相占い",
    nameEn: "Palmistry",
    description: "手のひらの線から運命・性格・恋愛・仕事運を読みます",
    origin: "インド・中国",
    icon: "🤚",
    category: "nature",
    inputType: "question",
  },
];

export const FORTUNE_CATEGORIES = {
  cards: { label: "カード・文字", color: "purple" },
  numbers: { label: "数と言葉", color: "blue" },
  astrology: { label: "星と天体", color: "indigo" },
  nature: { label: "自然と身体", color: "green" },
  eastern: { label: "東洋の叡智", color: "red" },
};
